# Generated by Django 4.0.2 on 2022-04-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financesManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeMachineRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('F', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('workspaceLimitX', models.FloatField(blank=True, null=True, verbose_name='Workspace Limit X')),
                ('workspaceLimitY', models.FloatField(blank=True, null=True, verbose_name='Workspace Limit Y')),
                ('workspaceLimitZ', models.FloatField(blank=True, null=True, verbose_name='Workspace Limit Z')),
                ('maxSpeed', models.FloatField(blank=True, null=True, verbose_name='Max Speed')),
                ('precision', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToolArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('cuttingDiameter', models.FloatField(default=0)),
                ('handleDiameter', models.FloatField(default=0)),
                ('cuttingLength', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('blades', models.IntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
                ('materials', models.ManyToManyField(to='toolsManager.Materials')),
                ('relation', models.ManyToManyField(through='toolsManager.ArchetypeMachineRelation', to='toolsManager.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cuttingDiameter', models.FloatField(default=0)),
                ('handleDiameter', models.FloatField(default=0)),
                ('cuttingLength', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('blades', models.IntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
                ('dateEntry', models.DateField()),
                ('dateScrap', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(max_length=10)),
                ('hours', models.IntegerField(blank=True, default=0)),
                ('stockPlace', models.CharField(blank=True, max_length=15, null=True)),
                ('speed', models.FloatField()),
                ('F', models.FloatField()),
                ('asignedMachine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolsManager.machine')),
                ('materials', models.ManyToManyField(to='toolsManager.Materials')),
                ('supplierOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financesManager.supplierorder')),
                ('toolArchetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolsManager.toolarchetype')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='materials',
            field=models.ManyToManyField(to='toolsManager.Materials'),
        ),
        migrations.AddField(
            model_name='archetypemachinerelation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsManager.machine'),
        ),
        migrations.AddField(
            model_name='archetypemachinerelation',
            name='toolArchetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsManager.toolarchetype'),
        ),
    ]
