# Generated by Django 4.0.2 on 2022-04-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolsManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolMachineRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('F', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsManager.machine')),
            ],
        ),
        migrations.RemoveField(
            model_name='toolarchetype',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='toolarchetype',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='F',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='asignedMachine',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='toolArchetype',
        ),
        migrations.AddField(
            model_name='tool',
            name='relations',
            field=models.ManyToManyField(through='toolsManager.ToolMachineRelation', to='toolsManager.Machine'),
        ),
        migrations.DeleteModel(
            name='ArchetypeMachineRelation',
        ),
        migrations.DeleteModel(
            name='ToolArchetype',
        ),
        migrations.AddField(
            model_name='toolmachinerelation',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsManager.tool'),
        ),
    ]
