# Generated by Django 4.0.2 on 2022-03-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=11, null=True)),
                ('country', models.CharField(blank=True, max_length=12, null=True)),
                ('personName', models.CharField(max_length=30)),
                ('personIdentification', models.CharField(blank=True, max_length=11, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('iban', models.CharField(blank=True, max_length=33, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('dateOrder', models.DateField()),
                ('dateTop', models.DateField(blank=True, null=True)),
                ('dateDelivery', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financesManager.client')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=11, null=True)),
                ('country', models.CharField(blank=True, max_length=12, null=True)),
                ('personName', models.CharField(max_length=30)),
                ('personIdentification', models.CharField(blank=True, max_length=11, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=10)),
                ('dateOrder', models.DateField()),
                ('dateDelivery', models.DateField(blank=True, null=True)),
                ('clientOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financesManager.clientorder')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financesManager.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('dateInvoice', models.DateField()),
                ('supplierOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financesManager.supplierorder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=80)),
                ('quantity', models.IntegerField(default=1)),
                ('priceUnitary', models.IntegerField(blank=True, null=True)),
                ('priceTotal', models.IntegerField()),
                ('dateTop', models.IntegerField(blank=True, null=True)),
                ('supplierOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financesManager.supplierorder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('priceUnitary', models.IntegerField(blank=True, null=True)),
                ('priceTotal', models.IntegerField()),
                ('dateTop', models.IntegerField(blank=True, null=True)),
                ('clientOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financesManager.clientorder')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('dateInvoice', models.DateField()),
                ('clientOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financesManager.clientorder')),
            ],
        ),
    ]
