# Generated by Django 4.0.2 on 2022-03-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financesManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('clientOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financesManager.clientorder')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('iban', models.CharField(blank=True, max_length=11, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('projects', models.ManyToManyField(blank=True, null=True, to='workersManager.Project')),
            ],
        ),
    ]
